# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamificationInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('target', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gamification.BadgeDefinition'),
        ),
        migrations.AddField(
            model_name='badge',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gamification.GamificationInterface'),
        ),
        migrations.AddField(
            model_name='badge',
            name='next_badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gamification.Badge'),
        ),
        migrations.AddField(
            model_name='badge',
            name='progression',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gamification.Progression'),
        ),
    ]
