# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0002_auto_20170822_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=timezone.now)),
                ('amount', models.BigIntegerField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gamification.GamificationInterface')),
            ],
        ),
    ]
