# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0003_pointchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='points',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
