# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0004_badge_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unlockable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('points_required', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gamification.GamificationInterface')),
            ],
        ),
        migrations.CreateModel(
            name='UnlockableDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('points_required', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='unlockable',
            name='unlockable_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gamification.UnlockableDefinition'),
        ),
    ]
