# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0005_auto_20170907_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointchange',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
