# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0006_auto_20170907_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgedefinition',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gamification.Category'),
        ),
        migrations.AddField(
            model_name='badgedefinition',
            name='points',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badgedefinition',
            name='progression_target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
