# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0007_auto_20170908_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='next_badge',
        ),
    ]
