# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0008_remove_badge_next_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='next_badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gamification.Badge'),
        ),
        migrations.AddField(
            model_name='badgedefinition',
            name='next_badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gamification.BadgeDefinition'),
        ),
    ]
