# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0009_auto_20171002_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
