# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 07:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0010_badge_revoked'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='badge',
            managers=[
                ('acquired_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
