# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0011_auto_20171006_0744'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='badge',
            managers=[
            ],
        ),
    ]
