# Generated by Django 2.0.3 on 2018-03-24 06:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('django_gamification', '0012_auto_20171006_0759'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='badge',
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='unlockable',
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
